### ISSUE TITLE
Does not listen on any available ports, documentation wrong, unicorn wrong, ports wrong

### ISSUE THREAD

**Issue by desrod** [Tobiadefami/six-degrees-of-torvalds#19]
I had high hopes for this, but alas, it looks like the whole project seems confused as to which ports it thinks it should be using, listening on and exposing. 

The docs say `http://0.0.0.0/8080`, but the nginx server exposes `8080`, and the final output from `docker compose up` shows some bogus subnet of `192.168.65.3`, on port `3000`. None of these work and none of these are valid. 

So which port _does_ this listen on, and how can we reach it, once the missing dependencies for `react-scripts` and `poetry lock` are fixed and satisfied? 

```
frontend-1  | Compiled successfully!
frontend-1  |
frontend-1  | You can now view degrees-of-connection in the browser.
frontend-1  |
frontend-1  |   Local:            http://localhost:3000
frontend-1  |   On Your Network:  http://192.168.65.3:3000
frontend-1  |
frontend-1  | Note that the development build is not optimized.
frontend-1  | To create a production build, use npm run build.
frontend-1  |
frontend-1  | webpack compiled successfully
```

**Comment by Tobiadefami** [comment]
Hello,

It appears there has been some confusion regarding the ports and IP addresses displayed by the Docker services. Since our application uses `network_mode: host`, all services are bound directly to your machine's network, without isolated Docker networking.

Here’s how you can access the services:
- **Nginx is configured to route traffic on port 8080.** You should access the application through `http://0.0.0.0:8080`.
- **The frontend development server runs on port 3000 during development,** and might display an internal Docker network IP (like 192.168.65.3), but this address is generally not necessary for accessing the application. You can also visit the frontend directly during development at `http://0.0.0.0:3000` if needed.

The [documentation](https://github.com/Tobiadefami/six-degrees-of-torvalds/blob/main/README.md) has been updated to reflect this setup better and prevent future confusion.
